Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%w': '()'
