# Sequel Database Configuration

development: "postgres://root@localhost/roda_graphql_development"
test: "postgres://root@localhost/roda_graphql_test"
production: "postgres://root@localhost/roda_graphql_production"
